modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL="https://github.com/aphrodite281/ATE-Efficient-Model-System/issues"

[[mods]]
modId = "ate_ems"
version = "${version}"
displayName = "Aphrodite's Transit Expansion - Efficient Model System"
displayURL = "https://github.com/aphrodite281/ATE-Efficient-Model-System"

authors = "Aphrodite281"
description = "An Efficient Model System, made by Aphrodite281."
logoFile = "icon.png"

displayTest = "IGNORE_ALL_VERSION"

[[dependencies.ate_ems]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ate_ems]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ate_ems]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"
