name: build
on: [ pull_request, push , workflow_dispatch ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        minecraft: [ 1.17.1, 1.18.2, 1.19.2, 1.19.3, 1.19.4, 1.20.1, 1.20.4 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '17.0.12'
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper/dists
            ~/.gradle/caches
            ./bin
            ./*/bin
            ./checkouts
          key: gradle-${{ matrix.minecraft }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Update serial number
        if: ${{ !startsWith(github.event.head_commit.message, 'rel') }}
        run: |
          sed -i "/^mod_version[[:space:]]*=/s/\(.*\)$/\1-${{ github.run_number }}/" gradle.properties
          cat gradle.properties
          grep "mod_version=" gradle.properties | cut -d'=' -f2

      - name: Build ${{ matrix.minecraft }}
        run: ./gradlew clean build -PbuildVersion="${{ matrix.minecraft }}" --no-daemon

      - name: Get Mod Version
        run: |
          MOD_VERSION=$(grep "mod_version=" gradle.properties | cut -d'=' -f2)
          if [[ "${{ github.event.head_commit.message }}" == rel* ]]; then
            MOD_VERSION="${MOD_VERSION}-${{ github.run_number }}"
          fi
          echo "MOD_VERSION=$MOD_VERSION"
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
      - name: Capture release artifacts individually
        uses: actions/upload-artifact@v4
        with:
          name: ATE-EMS-${{ env.MOD_VERSION }}+${{ matrix.minecraft }}
          path: build/*.jar
          compression-level: 9
  upload-collectively:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        with:
            fetch-depth: 0
        uses: actions/checkout@v4
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Get Mod Version
        run: |
          MOD_VERSION=$(grep "mod_version=" gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION=$MOD_VERSION"
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
      - name: Capture release artifacts collectively
        uses: actions/upload-artifact@v4
        with:
          name: ATE-EMS-${{ env.MOD_VERSION }}-${{ github.run_number }}
          path: artifacts/*.jar
          compression-level: 9
  github-release:
    if: startsWith(github.event.head_commit.message, 'rel -g') || startsWith(github.event.head_commit.message, 'rel -a') || startsWith(github.event.head_commit.message, 'rel -t')
    runs-on: ubuntu-latest
    needs: upload-collectively
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract changelog
        run: |
          chmod +x ./extract_changelog.sh
          ./extract_changelog.sh
      - name: Read changelog content
        id: read_changelog
        run: |
          
          CONTENT=$(cat extracted_changelog.md)
          
          # 使用EOF声明多行输出
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


      - name: Get Mod Version
        run: |
          MOD_VERSION=$(grep "mod_version=" gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: ATE-EMS-${{ github.run_number }}-${{ env.MOD_VERSION }}
          path: artifacts
          merge-multiple: true

      - name: Set current date
        run: echo "CUR_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Release
        if: ${{ !startsWith(github.event.head_commit.message, 'rel -t') }}
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.jar
          body: |
            更新日期: ${{ env.CUR_DATE }}
            工作流: [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            更新内容:
            ${{ steps.read_changelog.outputs.content }}
            
            相关链接:
            
          draft: false
          prerelease: false
          tag_name: ${{ env.MOD_VERSION }}
  modrinth-publish:
    if: startsWith(github.event.head_commit.message, 'rel -m') || startsWith(github.event.head_commit.message, 'rel -a') || startsWith(github.event.head_commit.message, 'rel -t')
    strategy:
      fail-fast: false
      matrix:
        minecraft: [ 1.17.1, 1.18.2, 1.19.2, 1.19.3, 1.19.4, 1.20.1, 1.20.4 ]
    runs-on: ubuntu-latest
    environment: modrinth
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Mod Version
        run: |
          MOD_VERSION=$(grep "mod_version=" gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
      - name: Extract changelog
        run: |
          chmod +x ./extract_changelog.sh
          ./extract_changelog.sh
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: ATE-EMS-${{ github.run_number }}-${{ env.MOD_VERSION }}+${{ matrix.minecraft }}
          path: artifacts
          merge-multiple: true
      - name: Show structure of downloaded files
        run: ls -R artifacts
      - name: Show require file name
        run: echo "artifacts/ATE-EMS-${{ env.MOD_VERSION }}+${{ matrix.minecraft }}.jar"
      - name: Modrinth Publish
        uses: Kir-Antipov/mc-publish@v3.3
        if: ${{ !startsWith(github.event.head_commit.message, 'rel -t') }}
        with:
          modrinth-id: ybOYitTg
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: artifacts/ATE-EMS-${{ env.MOD_VERSION }}+${{ matrix.minecraft }}.jar
          name: ATE-EMS-${{ env.MOD_VERSION }}+${{ matrix.minecraft }}
          version: ${{ env.MOD_VERSION }}+${{ matrix.minecraft }}
          version-type: release
          loaders: |
            fabric
            forge
          game-versions: ${{ matrix.minecraft }}
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
          # dependencies: []
          changelog-file: extracted_changelog.md
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write 
    # needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Download current artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     path: ./docs/artifacts
      #     merge-multiple: true
      - name: Display structure
        run: ls -R ./docs/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
